export const UI_LABELS = {
  common: {
    unexpectedError: "Unexpected error occurred",
    validationFailed: "Validation failed",
    noMeasurements: "No measurements",
    nullValue: "null",
  },
  dashboard: {
    sections: {
      sites: "Sites",
      manualMeasurementIngestion: "Manual Measurement Ingestion",
      selectedSiteMeasurements: "Selected Site Measurements",
    },
    tableHeaders: {
      siteName: "Site Name",
      siteType: "Site Type",
      status: "Status",
      compliance: "Compliance",
      emissionLimit: "Emission Limit",
      totalEmissionsToDate: "Total Emissions To Date",
      lastMeasurementAt: "Last Measurement At",
      actions: "Actions",
      id: "id",
      siteId: "Site ID",
      measuredAt: "Measured At",
      emissionValue: "Emission Value",
      unit: "unit",
    },
    emptyStates: {
      loadingSites: "Loading sites...",
      noSites: "No sites found. Create your first site to begin monitoring.",
      selectSiteToOpenForm:
        "Select Add Measurement on a site row to open this form.",
      noSiteSelected: "No site selected. Choose a site to view measurements.",
      loadingMeasurements: "Loading measurements...",
      noMeasurementsForSite: "No measurements exist for this site yet.",
    },
    actions: {
      addMeasurement: "Add Measurement",
      ingestMeasurement: "Ingest Measurement",
      cancel: "Cancel",
      saving: "Saving...",
    },
    form: {
      measuredAt: "Measured At",
      emissionValue: "Emission Value",
      unit: "Unit",
      rawPayload: "Raw Payload (JSON)",
      rawPayloadPlaceholder: '{"sensor":"A1","source":"manual"}',
    },
    messages: {
      siteListUpdatedRealtime: "Site list updated from realtime event.",
      measurementSaved: "Measurement saved successfully.",
      selectSiteBeforeSubmit: "Select a site before submitting measurement.",
      selectedSite: "Selected Site",
      compliance: "Compliance",
      lastMeasurement: "Last Measurement",
    },
  },
  siteDetail: {
    actions: {
      backToDashboard: "Back to Dashboard",
      addMeasurement: "Add Measurement",
      batchInsert: "Batch Insert",
      retryBatchInsert: "Retry Batch Insert",
      saving: "Saving...",
    },
    sections: {
      siteDetails: "Site Details",
      addSingleMeasurement: "Add Single Measurement",
      batchInsert: "Batch Insert",
      measurements: "Measurements",
    },
    headers: {
      siteName: "Site Name",
      siteType: "Site Type",
      status: "Status",
      complianceStatus: "Compliance Status",
      emissionLimit: "Emission Limit",
      totalEmissionsToDate: "Total Emissions To Date",
      rolling24hEmissions: "Rolling 24h Emissions",
      rolling30dEmissions: "Rolling 30d Emissions",
      latitude: "Latitude",
      longitude: "Longitude",
      lastMeasureAt: "Last Measure At",
      deleteAt: "Delete At",
      createdAt: "Created At",
      updatedAt: "Updated At",
      metadata: "Metadata",
      measuredAt: "Measured At",
      emissionValue: "Emission Value",
      unit: "unit",
      rawPayload: "Raw Payload (JSON)",
      id: "id",
      siteId: "Site ID",
      batchId: "Batch ID",
      measuredAtTable: "Measured At",
      emissionValueTable: "Emission Value",
      unitTable: "unit",
      createdAtTable: "Created At",
    },
    placeholders: {
      loadingSiteDetails: "Loading site details...",
      siteNotFound: "Site not found.",
      noMeasurementsForSite: "No measurements yet for this site.",
      rawPayload: '{"source":"manual_entry"}',
      batchCount: "Enter batch size (1-100)",
    },
    messages: {
      measurementAdded: "Measurement added successfully.",
      batchInsertDescription:
        "Generate fake telemetry via faker.js and ingest it as one idempotent batch. Retry uses the same client_batch_id to avoid duplicates.",
      batchInsertSuccess:
        "Batch ingestion completed successfully.",
      batchInsertDuplicate:
        "Batch was already processed earlier (duplicate retry detected).",
    },
    errors: {
      batchCountRange: "batch_count must be an integer between 1 and 100",
    },
  },
} as const;
