// This file was generated by Prisma, and assumes you have installed the following:
import { defineConfig } from "prisma/config";
import { loadEnv } from "./src/utils/loadEnv";

loadEnv();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node --loader ts-node/esm src/scripts/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
